name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
           node-version: 14

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: test
        run: yarn test --coverage
